# Generated by Django 3.2.8 on 2022-06-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20220620_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
