# Generated by Django 3.2.8 on 2022-06-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField(blank=True, null=True)),
                ('item_amount', models.TextField(blank=True, null=True)),
                ('item_category', models.TextField(blank=True, null=True)),
                ('expense_date', models.DateField()),
            ],
        ),
    ]
