# Generated by Django 4.0.5 on 2022-06-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_item_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='item_amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
